Brazil jumps to No. 2 in worldwide coronavirus cases, behind US
mbiesiad/COVID-19-World-Data pull request #45
Opened 2020-10-27 07:38 UTC by Praduman30642

Hey this Praduman Covid-19 tracker.

2020-10-27 07:58 UTC, mbiesiad commented
Hi @Praduman30642 great idea! But at this moment you're creating a new file here. Could you rename the file for 'News'?

![image](https://user-images.githubusercontent.com/18367606/97272073-b12e5580-1831-11eb-89a1-ce0268a0e354.png)

If so, with new name (News), could you put your current title "Brazil jumps to No. 2 in worldwide coronavirus cases, behind US" above/down the given code with link? + today' date

Please, rename the file. Put the title inside the field & add the current date.
News -> title "Brazil (...)" -> data & date

The file News should looks like:
# Title_1
Descr._1 / link, etc
date

Thanks! Best wishes

2020-10-27 08:00 UTC, mbiesiad requested changes

2020-10-27 08:00 UTC, mbiesiad commented on Brazil jumps to No. 2 in worldwide coronavirus cases, behind the US
> +<iframe src="https://ourworldindata.org/coronavirus-data-explorer?zoomToSelection=true&country=~BRA&region=World&casesMetric=true&interval=daily&hideControls=true&smoothing=0&pickerMetric=location&pi
Please add here
Brazil jumps to No. 2 in worldwide coronavirus cases, behind US
2020-10-27
& rename the file to News

2020-10-27 08:36 UTC, Praduman30642 commented
Done

2020-10-27 12:05 UTC, merged

2020-10-27 12:06 UTC, mbiesiad commented
Thanks. I will fix it, approved 🔥

2020-10-27 13:01 UTC, Praduman30642 commented
Very very thank you🙏🙏🙏

2020-10-27 13:06 UTC, Praduman30642 commented
It is not showing approved it's showing under review.
![image](https://user-images.githubusercontent.com/59205248/97305612-57567b80-1883-11eb-8327-3f8a6b5e8cc6.png)

2020-10-27 13:26 UTC, mbiesiad commented
My pleasure, and thank you too! Ok, I'll take a look at that (in the evening). Let's keep in touch :octocat:

2020-10-27 13:27 UTC, mbiesiad commented
By the way, what's about the 1st one? Everything is fine?

2020-10-27 15:00 UTC, Praduman30642 commented
The first one has same issue.

2020-10-27 15:16 UTC, mbiesiad commented
No, it's not. Everything is fine. Next time, please be sure about the Legend:
"Your PR has been accepted by a maintainer and is currently within the review period, which lasts for fourteen days."

You have to wait 14days now. It's not 'Pending' status, it's 'In Review' due to the rules.

Greetings

2020-10-28 14:25 UTC, mbiesiad commented
After this period, you will have icon like this

![image](https://user-images.githubusercontent.com/18367606/97449188-b4a90600-1931-11eb-96be-679271d06070.png)

Which means: "Accepted - Good job! Your PR has passed the review period and counts toward completing the Hacktoberfest challenge!"

2020-10-28 14:57 UTC, Praduman30642 commented
Thanks for informing me.😊😊😊😊